### PR TITLE
Feature/current commitments query map

### PR DESCRIPTION
**Pull request by hectoruch**

### CODE REVIEW

**Comment by hectoruch** [comment]
- New design on stories modal on map.

image

**Comment by edbrett** [comment]
Needs post date for stories in modal as discussed.

**Comment by edbrett** [comment]
Also modal breaks for header on long country names.

Close button moves when it should have absolute position:
screen shot 2017-04-07 at 08 23 24

Completely disappears for long country names:
screen shot 2017-04-07 at 08 23 34

**Comment by edbrett** [comment]
Also, do you want to merge this PR with irm-reports or with develop? Check branch at top.

**Comment by hectoruch** [comment]
Merge https://github.com/Vizzuality/ogp/pull/16

**Pull request merged**
